### PR TITLE
Add links to GQ

### PR DESCRIPTION
**Pull request by jeffabailey**
Preview: https://github.com/jeffabailey/managing-inner-source-projects/blob/master/measuring/use_gqm.md

### CODE REVIEW

**Comment by rrrutledge** [comment]
This is so 🆒, @jeffabailey❗ Does it render correctly in the _GitBook_ format that @spier enabled for us?

**Comment by spier** [comment]
Unfortunately the click events on the links don't work properly.
gitbook somehow tries to load the link within the same pane that the mermaid graph is rendered in, and that fails.

I saw that issue in the past already, and experimented with `target='_blank'` and similar but without success.

If you want to dig deeper, you can also contact the gitbook Support team to ask what mermaid features are supported in gitbook. Settings => Help => Contact Support

**Comment by jeffabailey** [comment]
Yes, it won't render correctly in GitBook.

@rrrutledge and I discussed making it work in GitHub for now, which when clicking links in GitHub it does work.

https://github.com/jeffabailey/managing-inner-source-projects/blob/master/measuring/use_gqm.md

Here's a discussion started to add Gitbook support for links.

https://github.com/GitbookIO/integrations/issues/240

**Review by rrrutledge — APPROVED** [review]

**Review by rrrutledge — APPROVED** [review]
So exciting for this!

**Pull request merged**
